### ISSUE TITLE
Missing some lines in the lib file but are available at github

### ISSUE THREAD

**Issue by ch-muhammad-adil** [Lyokone/flutterlocation#142]
Hello nice library, i have installed library from 
https://pub.dartlang.org/packages/location#-installing-tab- 

In library class these line were missing 
```
enum LocationAccuray { 
  POWERSAVE,
  LOW,
  BALANCED,
  HIGH,
  NAVIGATION
}

 Future<bool> changeSettings({LocationAccuray accuracy = LocationAccuray.HIGH, int interval = 5000}) =>
    _channel.invokeMethod('changeSettings',
    {
      "accuracy": accuracy.index,
      "interval": interval
    })
    .then((result) => result == 1);


```

 but in example i can see all these lines.

**Comment by ch-muhammad-adil** [comment]
Also anyway around to get the call back when user press "Allow" button in iOS ?

**Comment by Lyokone** [comment]
Hey ! These lines are from the 2.3 version which is not published yet ;) (and not documented as you can see). I should have probably keep it on another branch 😅

If you check permission, the return is a Future so you can listen to this to know if the button have been pressed. If you are talking about Location Service there is no way to listen to it on iOS due to Apple Limitation for App that are going on App Store.
