### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Xgamefactory** [Lyokone/flutterlocation#219]
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=34, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {c**************************.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(11378): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4589)
E/AndroidRuntime(11378): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4631)
E/AndroidRuntime(11378): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)

```

**Comment by luccascorrea** [comment]
This crash has been happening for me for a couple of months now. I see that the problem is line 397 in the file `android/src/main/java/com/lyokone/location/LocationPlugin.java`. More specifically, this call:

    if (this.checkServiceEnabled(null)) {

Inside the `checkServiceEnabled` method, at line 379, there is no check to make sure the `result` parameter is not null before calling `result.error()`

I'd submit a pull request but I am not sure how to do it, sorry.

PS: thanks for the library!
