### ISSUE TITLE
Inconsistent time format in IOS vs Android

### ISSUE THREAD

**Issue by j05u3** [Lyokone/flutterlocation#273]
I believe https://github.com/Lyokone/flutterlocation/blob/master/ios/Classes/LocationPlugin.m#L223 should be multiplied by 1000 to be in millis since epoch as in android

**Comment by 781flyingdutchman** [comment]
I just discovered the same thing: the iOS timestamp is in *seconds* since the epoch, and a) that is inconsistent with android's milliseconds since the epoch, and b) is not granular enough to do derivative calculations based on the time difference between two location updates (e.g. the rate of turn, based on delta heading divided by delta time).

**Comment by 781flyingdutchman** [comment]
Submitted a pull request (#277) for review
