### ISSUE TITLE
Issue after upgrading Flutter to 1.20.1

### ISSUE THREAD

**Issue by thedevteamza** [Lyokone/flutterlocation#398]
**Describe the bug**
Target of URI doesn't exist: 'package:location/location.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.darturi_does_not_exist

**Expected behavior**
No error should have been generated.

**Tested on:**
NA

**Other plugins:**
NA

**Additional logs**

``` shell
Target of URI doesn't exist: 'package:location/location.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.darturi_does_not_exist
```

**Comment by xpat** [comment]
I've had this error appear any number of times for this or other packages.  I usually resolve it easily by making sure to add the package in pubspec.yaml and running flutter get pub.  If you need to, review [the install step](https://pub.dev/packages/location/install). Otherwise it might help to post the output of flutter doctor -v.
