### ISSUE TITLE
_serviceEnabled = await location.serviceEnabled(); //block

### ISSUE THREAD

**Issue by cikichen** [Lyokone/flutterlocation#451]
**Describe the bug**
when running `_serviceEnabled = await location.serviceEnabled();`
The program is blocked.
Not responding

**Tested on:**
 - Android 8.0,sumsung galaxy s7 edge

**Comment by Atominac** [comment]
My app crashes when this line executes and gives androidruntime exception

Additional logs

E/AndroidRuntime(14321): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4097, result=-1, data=Intent { (has extras) }} to activity {com.kmguardini.guardini/com.example.guardini.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property plugin has not been initialized
E/AndroidRuntime(14321): at android.app.ActivityThread.deliverResults(ActivityThread.java:5009)
E/AndroidRuntime(14321): at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
E/AndroidRuntime(14321): at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(14321): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14321): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14321): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(14321): at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14321): at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(14321): at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime(14321): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14321): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(14321): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(14321): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property plugin has not been initialized
E/AndroidRuntime(14321): at com.example.guardini.MainActivity.onActivityResult(MainActivity.kt:22)
E/AndroidRuntime(14321): at android.app.Activity.dispatchActivityResult(Activity.java:8310)
E/AndroidRuntime(14321): at android.app.ActivityThread.deliverResults(ActivityThread.java:5002)
E/AndroidRuntime(14321): ... 11 more

**Comment by SilverCrow11** [comment]
try adding _serviceEnabled = await location.serviceEnabled() in a seperate async method and make sure you are initializing you Location variable before calling it

**Comment by Arkasher** [comment]
Same error here. The serviceEnabled method does not return and block the thread. Tested on motorola G7 Power.

**Comment by Lyokone** [comment]
Hi, let me know if it still happening on the 4.2.0 :) I fixed a bunch of Android stuffs.

**Comment by Atominac** [comment]
> Hi, let me know if it still happening on the 4.2.0 :) I fixed a bunch of Android stuffs.

I Will check and let you know :)
