### ISSUE TITLE
Platform Exception on MacOS

### ISSUE THREAD

**Issue by JayPerfetto** [Lyokone/flutterlocation#456]
My last issue was closed despite not being resolved or even commented on -

Describe the bug
Platform exception on mac OS ->

[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method serviceEnabled on channel lyokone/location)
#0 MethodChannel._invoke

Expected behavior
After enabling all of the sandbox settings, I should see the same behavior I see on iOS and android. Currently the project does not build for macos with the location plugin added

Tested on:

Android, real device
iOS, real device
Mac OS Desktop, real device
Additional logs
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-2.0.pre.34, on Mac OS X 10.15.4 19E287, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.0)
[✓] VS Code (version 1.24.1)
[✓] Connected device (3 available)

**Comment by bsneider** [comment]
Not sure if its related, but pod install kept failing, there was a missing file
LocationPlugin.m in ~/.pub-cache/hosted/pub.dartlang.org/location-3.1.0/macos/Classes
I manually added the file from https://github.com/Lyokone/flutterlocation/blob/master/location/darwin/Classes/LocationPlugin.m to that location and then it would install properly.

My current hypothesis is that the file was not included in the location package because of the delete file icon highlighted in the image below.
<img width="837" alt="DeletedFileIcon_LocationPlugin" src="https://user-images.githubusercontent.com/54788551/102725842-6c79e480-42df-11eb-9933-477ef2fbb849.png">
