### ISSUE TITLE
While building flutter app for android it automatically adds ACCESS_BACKGROUND_LOCATION and BACKGROUND_SERVICE automatically to build

### ISSUE THREAD

**Issue by vaimikpatel2908** [Lyokone/flutterlocation#473]
This is only happening I integrate the location plugin in my app. It works fine with the geolocator plugin. If you want to get more description on this issue then visit the stack overflow post where I have mentioned it briefly.

the versions I am using:
Location plugin: 3.2.1
Flutter: 1.22.5

[https://stackoverflow.com/questions/65579793/why-while-building-flutter-is-adding-access-background-location-and-foreground-s](url)

I am not sure whether it is a plugin issue or flutter's issue but when I removed the location plugin. To my surprise, it removed that background location and foreground service permissions from the build.

If  You need more information let me know I will provide as much as I can. Thanks.

**Comment by maciejpigulski** [comment]
This is basically beacuse of the added support for location to be used in background. Quick check revealed that Geolocator doesn't have background location support so it doesn't require such permissions.

**Comment by vaimikpatel2908** [comment]
It will be a problem for those who want to use your plugin for only foreground purposes, not in the background then they have to provide the information on play store like me that we are not using the location data in the background and still they rejected my app and suggested that to remove all unused permission which is not necessary. 

is there any solution for this scenario other than using the geolocator plugin?

**Comment by maciejpigulski** [comment]
That is a valid point. 

I think a solution to remove the hardcoded permissions from the plugin `AndroidManifest.xml` and adding a piece of documentation that you need to update your apps `AndroidManifest.xml` in order to use background mode could do the trick.

There is also the case of handling errors because of permissions not being added to the app and user trying to use the background mode. This needs verification for graceful handling. Other case is to rely that on the developer to know to add them and allow the app to fail (or crash).

So I think it's doable and should be done in the first place to be honest.

**Comment by vaimikpatel2908** [comment]
Yes, It would be great if you can deliver it as soon as possible before more people face the problem.

**Comment by adamshamsudeen** [comment]
checkout the solution in #471 to adddress the issue immediately.

**Comment by maciejpigulski** [comment]
Fixed in https://github.com/Lyokone/flutterlocation/pull/475, should be out soon.

**Comment by vaimikpatel2908** [comment]
Thanks
