### ISSUE TITLE
Issue While Gradle Build

### ISSUE THREAD

**Issue by sanjaymajoka** [Lyokone/flutterlocation#667]
I we are facing below issue while creating a build (debug/release) using **./gradlew build --stacktrace**

Could not determine the dependencies of task ':app:processDevProfileResources'.
> Could not resolve all task dependencies for configuration ':app:devProfileRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Somewhere In Stack Trace**

Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.google.android.gms:play-services-location:16.+.
Required by:Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.google.android.gms:play-services-location:16.+.
Required by:
    **project :app > project :location**
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Failed to list versions for com.google.android.gms:play-services-location.
    project :app > project :location
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Failed to list versions for com.google.android.gms:play-services-location.

**Comment by imatictz** [comment]
I'm facing the same issue!

**Comment by imatictz** [comment]
So I deleted the app from scratch and now it works fine! Try it out and let me know

**Comment by ddesarrollowc** [comment]
Same error here, seems like a nginx problem on bintray.com

**Comment by luckv** [comment]
But bintray should be closed.. or google.bintray.com was not closed?

**Comment by luckv** [comment]
> So I deleted the app from scratch and now it works fine! Try it out and let me know

What do you mean by "deleted the app from scratch"?

**Comment by cesarcamps** [comment]
Hi!!! I have this error too!! HOw to resolve this??

**Comment by ddesarrollowc** [comment]
@luckv is right, https://github.com/Lyokone/flutterlocation/issues/604

use geolocator instead.

**Comment by SogoGolf** [comment]
same issue here!

**Comment by yashpathack** [comment]
[Bintray is down](https://twitter.com/search?q=bintray&src=recent_search_click&f=live)
Prolly the [Bintray sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)is taking affect all over.

**Comment by yashpathack** [comment]
[Bintray is down](https://twitter.com/search?q=bintray&src=recent_search_click&f=live)
Prolly the [Bintray sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) is taking effect all over.

**Comment by yashpathack** [comment]
Moreover, saw few answers suggesting to replace all instances of `jcenter()` with `mavenCentral()`

**Comment by luckv** [comment]
The error build is from the row `api 'com.google.android.gms:play-services-location:16.+'` in the `build.gradle` file. Because search that dependency in repository at google.bintray.com, which is down.
Setting for this flutter plugin only, the gradle version to 7.1.1 (in gradle-wrapper.properties ) and the gradle plugin to 4.2.2 (in build.gradle) you can build using the repository google.maven.com, the current used android repository for google artifacts.

This is only a workaround, and I suggest to migrate to [`geolocator`](https://pub.dev/packages/geolocator) because this package seems not actively maintaned (last commit is from 6 months and no mention in the readme of the future of this package)

**Comment by itldeveloper4** [comment]
> > So I deleted the app from scratch and now it works fine! Try it out and let me know
> 
> What do you mean by "deleted the app from scratch"?

Never mind.. Still facing this issue..
By "deleted the app from scratch" means i just deleted the app from the phone and ran it again..

**Comment by magnuswikhog** [comment]
@luckv is right, the build error can be temporarily fixed by editing `build.gradle` of the location plugin.

The steps listed below are for IntelliJ IDEA, things probably look slightly different in other IDE's.

1. In the Project tool window (where your files are listed), scroll all the way down until you find `Flutter Plugins`. If you don't see it, make sure that `Project` is selected in the dropdown at the top of the Project tool window.
2. Open `Flutter plugins`, find `location-4.0.0` and open it (you might have a different version number after `location-`, that's fine).
3. Open the file `location-4.0.0/android/build.gradle`
4. Find the line `api 'com.google.android.gms:play-services-location:16.+'`
5. Change it to `api 'com.google.android.gms:play-services-location:16.0.0'`. If your editor says that the file does not belong to your project, select `"I want to edit this file anyway"`.

You should now be able to build the app. 

[Original answer on Stackoverflow](https://stackoverflow.com/a/70319873/930640)

**Comment by sami-samcla** [comment]
This worked for me:

```
dependencies {
...
  constraints {
    implementation('com.google.android.gms:play-services-location') {
        version {
            strictly "16.0.0"
        }
        because 'location: 3.2.4 does not specify version & google.bintray.com answers 502 Bad Gateway'
    }
  }
}
```
Original answer: https://stackoverflow.com/questions/70166663/could-not-get-play-services-location-maven-metadata-xml-received-status-code
