### ISSUE TITLE
Please update ext.kotlin_version = '1.4.20' to latest

### ISSUE THREAD

**Issue by MdFarhanRaja** [Lyokone/flutterlocation#794]
Please update ext.kotlin_version = '1.4.20' to latest. Not able to generate appcenter build

**Comment by asaarnak** [comment]
Duplicate issue: #762

**Comment by 781flyingdutchman** [comment]
H @Lyokone , I create a possible pull request for this (it's a minor change) but because you only have a tag pointing to the latest V4 version (and not a branch) I cannot create the actual pull request. If you can create a branch at that point I am happy to create the request, or simply update the ext.kotlin_version in build.gradle to 1.7.0 so this package compiles with current versions of the gradle plugin. Thanks!

**Comment by 781flyingdutchman** [comment]
I had the same issue and believe the author is focused on V5 and not currently maintaining V4. I forked the V4 version and updated the gradle plugin version.  Until the author fixes this you can use my fork in the pubspec.yaml:
```
location:
    git:
      url: git@github.com:781flyingdutchman/flutterlocation.git
      ref: V4 
```

**Comment by bartekpacia** [comment]
This is fixed in the latest v5 versions.
