### ISSUE TITLE
Please udpate the package and fix the dependeny issues caused by flutter 3.24 and this web

### ISSUE THREAD

**Issue by fisforfaheem** [Lyokone/flutterlocation#983]
Because location_web 5.0.3 depends on web ^0.5.1 and no versions of location_web match >5.0.3 <6.0.0, location_web ^5.0.3 requires web ^0.5.1.
And because get >=5.0.0-release-candidate-8 depends on web ^1.0.0, get >=5.0.0-release-candidate-8 is incompatible with location_web ^5.0.3.
And because location 7.0.0 depends on location_web ^5.0.3 and no versions of location match >7.0.0 <8.0.0, get >=5.0.0-release-candidate-8 is incompatible with location ^7.0.0.
So, because depends on both get ^5.0.0-release-candidate-8 and location ^7.0.0, version solving failed.
exit code 1

**Comment by Abdulvaliy** [comment]
Same error

Because location_web 5.0.3 depends on web ^0.5.1 and no versions of location_web match >5.0.3 <6.0.0, location_web ^5.0.3 requires web ^0.5.1.
And because share_plus >=10.0.1 depends on web ^1.0.0, share_plus >=10.0.1 is incompatible with location_web ^5.0.3.
And because location 7.0.0 depends on location_web ^5.0.3 and no versions of location match >7.0.0 <8.0.0, share_plus >=10.0.1 is incompatible with location ^7.0.0.
So, because ant_ex depends on both location ^7.0.0 and share_plus ^10.0.2, version solving failed.

**Comment by Abdulvaliy** [comment]
@Lyokone can you fix the issue?

**Comment by Hassico** [comment]
If you are still facing this issue, the author has bumped the version for `web` to `1.0.0` but has not released an update to pub. In the meantime you can reference the repo from github like this:

  location_workspace:
    git:
      url: https://github.com/Lyokone/flutterlocation.git
      ref: master

**Comment by fisforfaheem** [comment]
sure

**Comment by mulderpf** [comment]
> If you are still facing this issue, the author has bumped the version for `web` to `1.0.0` but has not released an update to pub. In the meantime you can reference the repo from github like this:
> 
> ```
>   location_workspace:
>     git:
>       url: https://github.com/Lyokone/flutterlocation.git
>       ref: master
> ```

This doesn't work for me.  I'm stuck and cannot update to the latest Firebase packages without this breaking :(

**Comment by fisforfaheem** [comment]
Hope all packages support this upgrade

**Comment by adeeteya** [comment]
Getting this error still:-

Because location >=7.0.0 depends on location_web ^5.0.3 which depends on web ^0.5.1, location >=7.0.0 requires web ^0.5.1.
And because file_picker >=8.1.0 depends on web ^1.0.0, location >=7.0.0 is incompatible with file_picker >=8.1.0.
So, because *[secret_project_name]* depends on both file_picker ^8.1.2 and location ^7.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on location: flutter pub add location:^6.0.2

I really don't want to downgrade the package @Lyokone could you upload your new version to pub please?

**Comment by Mounix99** [comment]
> If you are still facing this issue, the author has bumped the version for `web` to `1.0.0` but has not released an update to pub. In the meantime you can reference the repo from github like this:
> 
> ```
>   location_workspace:
>     git:
>       url: https://github.com/Lyokone/flutterlocation.git
>       ref: master
> ```

If you want to override `location` package you need to add path
```yaml
  location:
    git:
      url: https://github.com/Lyokone/flutterlocation
      path: packages/location
```
but this version doesn't include reference to latest `location_web` so to override only `location_web` you need to 
```yaml
  location_web:
    git:
      url: https://github.com/Lyokone/flutterlocation
      path: packages/location_web
```
but seems like there is an issue with syntax 

>  Error on line 20, column 8 of ../../.pub-cache/git/flutterlocation-c5b523c528a5752b86da1224c7c437180e073ce3/packages/location_web/pubspec.yaml: Invalid version constraint: Expected version number after ">=" in ">=^0.5.1 <2.0.0", got "^0.5.1 <2.0.0".
>    ╷
> 20 │   web: ">=^0.5.1 <2.0.0"
>    │        ^^^^^^^^^^^^^^^^^
>    ╵

   
   @Lyokone can you please help with that and prepare release, it is blocking a lot

**Comment by ramankanabi** [comment]
any news?

**Comment by Juggler98** [comment]
Try this:

`  location:
    git:
      url: https://github.com/Juggler98/flutterlocation
      path: packages/location
      ref: 1cc9cae16b9a58de74ffaf8113cb86e247d25739`

**Comment by bartekpacia** [comment]
Hey, does this still occur?

**Comment by Juggler98** [comment]
@bartekpacia no, it's solved. The issue should be closed.

**Comment by bartekpacia** [comment]
Thanks for confirming!
