### ISSUE TITLE
need new version

### ISSUE THREAD

**Issue by ImanGhasemiArani** [Lyokone/flutterlocation#999]
hi, 
please develop new version.

**Comment by xunreal75** [comment]
Please consider to make clear requests, send code and describe the issue.

**Comment by richardparulian** [comment]
I'am using Dart version 3.5.3, Flutter version 3.24 & Location version 6.0.2 received a log like this:

warning: [deprecation] PRIORITY_NO_POWER in LocationRequest has been deprecated put(0, LocationRequest.PRIORITY_NO_POWER);

warning: [deprecation] PRIORITY_LOW_POWER in LocationRequest has been deprecated put(1, LocationRequest.PRIORITY_LOW_POWER);

warning: [deprecation] PRIORITY_BALANCED_POWER_ACCURACY in LocationRequest has been deprecated put(2, LocationRequest.PRIORITY_BALANCED_POWER_ACCURACY);

warning: [deprecation] PRIORITY_HIGH_ACCURACY in LocationRequest has been deprecated put(3, LocationRequest.PRIORITY_HIGH_ACCURACY);

warning: [deprecation] PRIORITY_HIGH_ACCURACY in LocationRequest has been deprecated put(4, LocationRequest.PRIORITY_HIGH_ACCURACY);

warning: [deprecation] PRIORITY_LOW_POWER in LocationRequest has been deprecated put(5, LocationRequest.PRIORITY_LOW_POWER);

warning: [deprecation] isFromMockProvider() in Location has been deprecated if (location.isFromMockProvider()) 

warning: [deprecation] create() in LocationRequest has been deprecated mLocationRequest = LocationRequest.create();

warning: [deprecation] setInterval(long) in LocationRequest has been deprecated mLocationRequest.setInterval(this.updateIntervalMilliseconds);

warning: [deprecation] setFastestInterval(long) in LocationRequest has been deprecated mLocationRequest.setFastestInterval(this.fastestUpdateIntervalMilliseconds);

warning: [deprecation] setPriority(int) in LocationRequest has been deprecated  mLocationRequest.setPriority(this.locationAccuracy);

warning: [deprecation] setSmallestDisplacement(float) in LocationRequest has been deprecated  mLocationRequest.setSmallestDisplacement(this.distanceFilter);

warning: [deprecation] Long(long) in Long has been deprecated final Long updateIntervalMilliseconds = new Long((int) call.argument("interval"));

warning: [deprecation] Float(double) in Float has been deprecated final Float distanceFilter = new Float((double) call.argument("distanceFilter"));

if i using location version 7.0.0 log like this:

Because no versions of file_picker match >8.1.2 <9.0.0 and file_picker 8.1.2 depends on web ^1.0.0, file_picker ^8.1.2 requires web ^1.0.0.
And because location >=7.0.0 depends on location_web ^5.0.3 which depends on web ^0.5.1, file_picker ^8.1.2 is incompatible with location >=7.0.0.
So, because hris depends on both location ^7.0.0 and file_picker ^8.1.2, version solving failed.

**Comment by bartekpacia** [comment]
hi,
please learn how to create high-quality issues.
